# ----------- CONFIGURABLE START -----------
title:            "Leah’s Swing Dance"
description:      "怡的回旋舞步"
url:              http://leah.li # Website
signoff:          "Leah" # Your name

# Owner/author information
owner:
  name:           Leah Li
  author:         Leah
  avatar:         Leah.png
  email:          nankailiyi@live.cn  
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    "你看 我想要的东西好多。我可能什么都想要：那每回无限旋落的黑暗 以及每一个步伐升盈令人战栗的光辉。"
  favicon:        favicon.ico
  # Social networking links used in footer. Update and remove as you like.
  twitter:        #
  facebook:       Leah-Li
  github:         Leah-li
  stackexchange:  #
  linkedin:       #
  instagram:      Liyi_Leah
  flickr:         #


# Links to include in footer navigation
# For external links add external: true
links:
  - name:         Home
    url:          /
    external:     true
  - name:         Books 
    url:          /Books
    external:     true
  - name:         Archives
    url:          /Archives
    external:     false
  - name:         Tags
    url:          /Tags
    external:     false
  - name:         About
    url:          /About
    external:     true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:         Asia/Shanghai
future:           true
highlighter:      pygments
markdown:         kramdown
paginate:         6
paginate_path:    "Page:num"
gems: 
                  - jekyll-paginate

# 分页
paginate: 15
# paginate_path:    "liberxuepage:num"
gems:             [jekyll-paginate]

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:        /:categories/:title
defaults:
  - values:
      layout:     "default"


kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

# Defaults for posts
imagefeature:    "fantasy.jpg" # We don't want posts without a header image, that whould mean white on white
bg-image:        "/style/bg-ico.png"

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
facebook_appid:   #
share:            true 


# Comments
disqus_shortname: #
